---
kind: pipeline
name: default-image-push-pull

concurrency:
  limit: 1

platform:
  os: linux
  arch: amd64

steps:
  - name: validate-list
    image: library/ubuntu:21.04
    commands:
    - grep -vE '^\s*(#|//)' images-list | sort -Vc
    - grep -vE '^\s*(#|//)' images-list-daily | sort -Vc
  # this step will run on every push
  - name: mirror-images
    image: rancher/dapper:v0.5.7
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    commands:
      - cat images-list | dapper
    settings:
      custom_dns: 1.1.1.1
    when:
      event:
        - push
  # this step will run on every push, and also via cron every day
  - name: mirror-images-daily
    image: rancher/dapper:v0.5.7
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    commands:
      - cat images-list-daily | dapper
    settings:
      custom_dns: 1.1.1.1
    when:
      event:
      - push
      - cron

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
