name: Add tag to existing image
on:
  workflow_dispatch:
    inputs:
      images:
        type: string
        description: "Comma separated list of existing images"
        required: true
      tags:
        type: string
        description: "Comma separated list of tags to add"
        required: true

env:
  IMAGES: ${{ inputs.images }}
  TAGS: ${{ inputs.tags }}

permissions:
  contents: write
  pull-requests: write
jobs:
  add-tag-to-existing-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Run add-tag-to-existing-image.sh
        run: make add-tag-to-existing-image.sh
      - name: Check for repository changes
        run: |
          if git diff --name-only --exit-code; then
            echo "No changes found in repository"
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "Changes found in repository"
            git diff --name-only
            echo "changes_exist=true" >> $GITHUB_ENV
          fi
      - name: Create branch, commit and push
        if: ${{ env.changes_exist == 'true' }}
        id: branch
        run: |
          BRANCH="githubaction-add-tag-$(date +%Y-%m-%d-%H-%M-%S)"
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b "$BRANCH"
          git commit -a -m "Adding new tag(s) for image(s) ${IMAGES}"
          git push origin "$BRANCH"
      - name: Create Pull Request
        if: ${{ env.changes_exist == 'true' }}
        id: cpr
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # v6.3.3
        env:
          SOURCE_BRANCH: ${{ steps.branch.outputs.branch }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { IMAGES, TAGS, SOURCE_BRANCH, GITHUB_ACTOR } = process.env

            let body = `Images: ${IMAGES}\nTags: ${TAGS}\n\nAuto-generated by GitHub Actions, initiated by @${GITHUB_ACTOR}\n`

            const { data: pr } = await github.rest.pulls.create({
              title: `Adding new tag(s) for image(s) ${IMAGES}`,
              body: body,
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "${{ github.ref_name }}",
              head: `${SOURCE_BRANCH}`
            });
            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number: pr.number,
              labels: ["status/auto-created"],
            });
            console.log('Created new pull request');
            return pr.html_url;
      - name: Check outputs
        if: ${{ env.changes_exist == 'true' }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.result }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.result }}" >> $GITHUB_STEP_SUMMARY
