name: Add tag to existing image
run-name: Add tag(s) ${{ inputs.tags }} to image(s) ${{ inputs.images }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      images:
        type: string
        description: "Comma separated list of existing images"
        required: true
      tags:
        type: string
        description: "Comma separated list of tags to add"
        required: true

env:
  IMAGES: ${{ inputs.images }}
  TAGS: ${{ inputs.tags }}

permissions:
  contents: write
  pull-requests: write
jobs:
  add-tag-to-existing-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Run add-tag-to-existing-image.sh
        run: make add-tag-to-existing-image.sh
      - name: Check for repository changes
        run: |
          if git diff --name-only --exit-code; then
            echo "No changes found in repository"
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "Changes found in repository"
            git diff --name-only
            echo "changes_exist=true" >> $GITHUB_ENV
          fi
      - name: Create branch, commit and push
        if: ${{ env.changes_exist == 'true' }}
        id: branch
        run: |
          BRANCH="gha-add-tag-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b "$BRANCH"
          git commit -a -m "Adding new tag(s) for image(s) ${IMAGES}"
          git push origin "$BRANCH"
      - name: Create Pull Request
        if: ${{ env.changes_exist == 'true' }}
        id: cpr
        env:
          SOURCE_BRANCH: ${{ steps.branch.outputs.branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Images: ${IMAGES}" >> $GITHUB_STEP_SUMMARY
          echo "Tags: ${TAGS}" >> $GITHUB_STEP_SUMMARY
          PR_TITLE="Added tag(s) ${TAGS} for image(s) ${IMAGES}"
          EXISTING_PR=$(gh pr list --limit 1500 --json title,url | jq --arg title "${PR_TITLE}" -r '.[] | select(.title==$title) | .url')
          if [ -z "${EXISTING_PR}" ]; then
              PR_BODY="$(echo -e Images: ${IMAGES}\\nTags: ${TAGS}\\n\\nAuto-generated by GitHub Actions, initiated by @${GITHUB_ACTOR}\\n)"
              CREATED_PR=$(gh pr create --title "${PR_TITLE}" --body "${PR_BODY}" --label "status/auto-created" --base "${GITHUB_REF_NAME}" --head "${SOURCE_BRANCH}")
              echo "Created pull request: ${CREATED_PR}" >> $GITHUB_STEP_SUMMARY
          else
              echo "Pull request already exists: ${EXISTING_PR}" >> $GITHUB_STEP_SUMMARY
          fi
